version: '3.8'
services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://service-db:3306/test
  service-db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: '31072002oisvK'
    ports:
      - "3307:3306"