version: '3.8'
services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/test
  mysql:
    image: mysql:8.0.33
    container_name: 'java-mysql'
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: '31072002oisvK'
      MYSQL_DB: 'test'
    ports:
      - "3307:3306"
